.gitignore, CHANGELOG.md, examples/examples-by-ml-library/pytorch-lightning/Makefile, examples/examples-by-ml-library/pytorch-lightning/main.py, examples/examples-by-ml-library/pytorch-lightning/requirements.txt, modelstore/models/managers.py, modelstore/models/pytorch_lightning.py, modelstore/models/pytorchlightning.py, requirements-dev.txt, tests/models/test_managers.py, tests/models/test_pytorch.py, tests/models/test_pytorch_lightning.py
Requested here: https://github.com/operatorai/modelstore/issues/13
=> Add pytorch-lightning to modelstore

CHANGELOG.md, examples/examples-by-ml-library/sklearn/main.py, modelstore/models/pytorch.py, modelstore/models/sklearn.py, modelstore/models/util.py, modelstore/storage/blob_storage.py, modelstore/storage/local.py, setup.py, tests/models/test_sklearn.py
Currently, trying to upload a pipeline results in `TypeError: Object of type StandardScaler is not JSON serializable`
=> Add support for sklearn pipelines

CHANGELOG.md, examples/Makefile-example, examples/examples-by-storage/demos.py, examples/examples-by-storage/main.py, modelstore/model_store.py, modelstore/storage/aws.py, modelstore/storage/azure.py, modelstore/storage/blob_storage.py, modelstore/storage/gcloud.py, modelstore/storage/hosted.py, modelstore/storage/local.py, modelstore/storage/storage.py, tests/storage/test_aws.py, tests/storage/test_azure.py, tests/storage/test_blob_storage.py, tests/storage/test_gcloud.py, tests/storage/test_local.py, tests/storage/test_utils.py
https://github.com/operatorai/modelstore/issues/82
=> Enable unsetting model states

examples/examples-by-storage/Makefile, examples/examples-by-storage/demos.py, examples/examples-by-storage/main.py, examples/examples-by-storage/run-all.sh, modelstore/storage/blob_storage.py
https://github.com/operatorai/modelstore/issues/91
=> Fix logging bug when downloading latest model

CHANGELOG.md, modelstore/models/pytorch.py, tests/models/test_pytorch.py
https://github.com/operatorai/modelstore/issues/94
=> Pytorch upload without optim

CHANGELOG.md, modelstore/models/fastai.py, requirements-dev.txt, tests/models/test_fastai.py
https://github.com/operatorai/modelstore/issues/95
=> Change fastai import paths depending on fastai version

CHANGELOG.md, modelstore/models/sklearn.py, tests/models/test_sklearn.py
https://github.com/operatorai/modelstore/issues/96
=> Remove metadata from sklearn pipelines

requirements-dev1.txt
https://github.com/operatorai/modelstore/security/dependabot/2
=> Upgrade pytorch-lightning==1.5.10

modelstore/model_store.py, modelstore/storage/blob_storage.py, modelstore/storage/local.py, modelstore/storage/states/model_states.py, modelstore/storage/storage.py, modelstore/storage/util/paths.py, tests/storage/states/test_model_states.py, tests/storage/test_blob_storage.py, tests/storage/util/test_paths.py, tests/test_model_store.py
Creates a `class ReservedModelStates(Enum)`, which will be used for model state changes that are automatically handled by `modelstore`. It currently contains a single reserved state ("deleted").
=> Create reserved model states

.github/workflows/python-package.yml, modelstore/meta/revision.py
Unit tests aren't running when contributors open a pull request, so this PR amends when the checks are run to include pull requests that target the `main` branch.
=> Set tests to run on push and pull_request

.github/workflows/python-package.yml
This makes all workflows run with the same conditions
=> Update workflow conditions

modelstore/storage/gcloud.py, tests/storage/test_gcloud.py
This PR implements my two suggestions from this PR:
- https://github.com/operatorai/modelstore/pull/142
=> Clean up anonymous access in GCP

CHANGELOG.md, modelstore/ids/model_ids.py, modelstore/model_store.py, modelstore/models/model_manager.py, modelstore/storage/local.py, tests/ids/test_model_ids.py, tests/models/test_missing_manager.py, tests/models/test_model_manager.py, tests/test_model_store.py, tests/test_model_store_filesystem.py, tests/test_model_store_gcp.py, tests/test_utils.py
This PR addresses the feedback that I left in @cdknorow's PR below
Relevant PRs:
- https://github.com/operatorai/modelstore/pull/147
- https://github.com/operatorai/modelstore/pull/160
=> Finish enabling users to set the model_id when saving model

requirements.txt
=> Add `numpy` as a dependency

CHANGELOG.md, modelstore/storage/gcloud.py, modelstore/utils/log.py, tests/storage/test_gcloud.py
Aims to fix:
- https://github.com/operatorai/modelstore/issues/173
=> Google cloud error (ValueError: Anonymous credentials cannot be refreshed)

modelstore/models/xgboost.py
Adds support for xgb.core.Booster to operatorai modelstore to solve this issue: https://github.com/operatorai/modelstore/issues/169
=> add xgb.core.Booster support to operatorai modelstore

CHANGELOG.md, examples/examples-by-ml-library/libraries/xgboost_booster_example.py, examples/examples-by-ml-library/main.py, examples/examples-by-ml-library/run-all.sh, modelstore/models/xgboost.py, tests/models/test_xgboost.py
Follows on from:
- https://github.com/operatorai/modelstore/pull/170
=> Extend tests for xgb.Booster types

CHANGELOG.md, modelstore/metadata/metadata.py, modelstore/metadata/utils/utils.py, modelstore/models/model_manager.py, tests/metadata/test_metadata.py, tests/metadata/utils/test_utils.py, tests/test_model_store.py
Feature suggested here:
- https://github.com/operatorai/modelstore/issues/184
=> Add extra meta data when uploading a model

CHANGELOG.md, modelstore/models/model_manager.py, tests/models/test_model_manager.py
For clarity, after adding `extra_metadata`
- https://github.com/operatorai/modelstore/pull/185
=> Rename extras= to extra_files=

CHANGELOG.md, examples/examples-by-ml-library/main.py, modelstore/model_store.py, modelstore/storage/minio.py, workflows/Makefile, workflows/main.py
Fixes a small bug from:
- https://github.com/operatorai/modelstore/pull/223
Which broke the workflows
=> Fix MinIO argument ordering

.github/workflows/unit-tests.yml, .gitignore, CHANGELOG.md, bin/_pyenv_config, examples/Makefile-example, examples/examples-by-ml-library/libraries/yolo_example.py, examples/examples-by-ml-library/main.py, examples/examples-by-ml-library/run-all.sh, setup.py
MLOps Community Slack thread:
https://mlops-community.slack.com/archives/C0227QJCDS8/p1677954347775149?thread_ts=1677929306.961269&cid=C0227QJCDS8
=> Add Python 3.9 support

examples/examples-by-ml-library/libraries/huggingface/dpt.py, examples/examples-by-ml-library/main.py, modelstore/models/transformers.py
https://mlops-community.slack.com/archives/C0227QJCDS8/p1683731515789489
=> Add support for DPT models

CHANGELOG.md, examples/examples-by-ml-library/main.py, examples/examples-by-ml-library/run-all.sh, modelstore/models/tensorflow.py, modelstore/models/transformers.py, setup.py
Fixes and improvements
- https://github.com/operatorai/modelstore/issues/233
- https://github.com/operatorai/modelstore/issues/232
- https://github.com/operatorai/modelstore/issues/228
=> Release modelstore==0.0.79

examples/README.md
=> Fix examples documentation

CHANGELOG.md, README.md, modelstore/model_store.py, modelstore/storage/blob_storage.py, modelstore/storage/storage.py, tests/models/test_lightgbm.py, tests/storage/test_blob_storage_states.py
=> Delete model states completely

CHANGELOG.md, modelstore/model_store.py, modelstore/storage/blob_storage.py, modelstore/storage/storage.py, tests/storage/test_blob_storage_states.py
=> Get the model states for a specific model

CHANGELOG.md, modelstore/model_store.py, modelstore/models/model_manager.py
=> Add clean up steps that catch KeyboardInterrupt

CHANGELOG.md, CONTRIBUTING.md, Dockerfile, Makefile, README.md, examples/examples-by-ml-library/main.py, examples/examples-by-ml-library/modelstores.py, examples/examples-by-ml-library/requirements.txt, examples/examples-by-ml-library/run-all.sh, requirements-dev1.txt, requirements.txt, setup.py
Test:
https://test.pypi.org/project/modelstore/0.0.81/
Release: ⏲️
=> Release modelstore==0.0.81
